/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface HederaTokenServiceInterface extends ethers.utils.Interface {
  functions: {
    "redirectForToken(address,bytes)": FunctionFragment;
    "transferFrom(address,address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "redirectForToken",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "redirectForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;

  events: {
    "CallResponseEvent(bool,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CallResponseEvent"): EventFragment;
}

export class HederaTokenService extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: HederaTokenServiceInterface;

  functions: {
    redirectForToken(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "redirectForToken(address,bytes)"(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,address,uint256)"(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  redirectForToken(
    token: string,
    encodedFunctionSelector: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "redirectForToken(address,bytes)"(
    token: string,
    encodedFunctionSelector: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFrom(
    token: string,
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,address,uint256)"(
    token: string,
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    redirectForToken(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      responseCode: BigNumber;
      response: string;
      0: BigNumber;
      1: string;
    }>;

    "redirectForToken(address,bytes)"(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      responseCode: BigNumber;
      response: string;
      0: BigNumber;
      1: string;
    }>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,address,uint256)"(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    CallResponseEvent(undefined: null, undefined: null): EventFilter;
  };

  estimateGas: {
    redirectForToken(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "redirectForToken(address,bytes)"(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,address,uint256)"(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    redirectForToken(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "redirectForToken(address,bytes)"(
      token: string,
      encodedFunctionSelector: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,address,uint256)"(
      token: string,
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
