/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IHTS1644Interface extends ethers.utils.Interface {
  functions: {
    "controllerRedeem(address,bytes32,uint256,bytes,bytes)": FunctionFragment;
    "controllerTransfer(address,address,bytes32,uint256,bytes,bytes)": FunctionFragment;
    "isControllable()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "controllerRedeem",
    values: [string, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controllerTransfer",
    values: [string, string, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isControllable",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "controllerRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isControllable",
    data: BytesLike
  ): Result;

  events: {
    "ControllerRedemption(address,address,uint256,bytes,bytes)": EventFragment;
    "ControllerTransfer(address,address,address,bytes32,uint256,bytes,bytes)": EventFragment;
    "FinalizedControllerFeature()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ControllerRedemption"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ControllerTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FinalizedControllerFeature"): EventFragment;
}

export class IHTS1644 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IHTS1644Interface;

  functions: {
    controllerRedeem(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "controllerRedeem(address,bytes32,uint256,bytes,bytes)"(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    controllerTransfer(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "controllerTransfer(address,address,bytes32,uint256,bytes,bytes)"(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isControllable(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "isControllable()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;
  };

  controllerRedeem(
    _tokenHolder: string,
    _partition: BytesLike,
    _value: BigNumberish,
    _data: BytesLike,
    _operatorData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "controllerRedeem(address,bytes32,uint256,bytes,bytes)"(
    _tokenHolder: string,
    _partition: BytesLike,
    _value: BigNumberish,
    _data: BytesLike,
    _operatorData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  controllerTransfer(
    _from: string,
    _to: string,
    _partition: BytesLike,
    _value: BigNumberish,
    _data: BytesLike,
    _operatorData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "controllerTransfer(address,address,bytes32,uint256,bytes,bytes)"(
    _from: string,
    _to: string,
    _partition: BytesLike,
    _value: BigNumberish,
    _data: BytesLike,
    _operatorData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isControllable(overrides?: CallOverrides): Promise<boolean>;

  "isControllable()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    controllerRedeem(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "controllerRedeem(address,bytes32,uint256,bytes,bytes)"(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    controllerTransfer(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "controllerTransfer(address,address,bytes32,uint256,bytes,bytes)"(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    isControllable(overrides?: CallOverrides): Promise<boolean>;

    "isControllable()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    ControllerRedemption(
      _controller: null,
      _tokenHolder: string | null,
      _value: null,
      _data: null,
      _operatorData: null
    ): EventFilter;

    ControllerTransfer(
      _controller: null,
      _from: string | null,
      _to: string | null,
      _partition: null,
      _value: null,
      _data: null,
      _operatorData: null
    ): EventFilter;

    FinalizedControllerFeature(): EventFilter;
  };

  estimateGas: {
    controllerRedeem(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "controllerRedeem(address,bytes32,uint256,bytes,bytes)"(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    controllerTransfer(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "controllerTransfer(address,address,bytes32,uint256,bytes,bytes)"(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isControllable(overrides?: CallOverrides): Promise<BigNumber>;

    "isControllable()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    controllerRedeem(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "controllerRedeem(address,bytes32,uint256,bytes,bytes)"(
      _tokenHolder: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    controllerTransfer(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "controllerTransfer(address,address,bytes32,uint256,bytes,bytes)"(
      _from: string,
      _to: string,
      _partition: BytesLike,
      _value: BigNumberish,
      _data: BytesLike,
      _operatorData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isControllable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isControllable()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
